In [4]:
import pandas as pd

# Lets Load the Json First

In [7]:
Oct = pd.read_json('tweetsOct.json')
Oct.head()

,fullname,html,id,likes,replies,retweets,text,timestamp,url,user
0,zentrade.online,"<p class=""TweetTextSize js-tweet-text tweet-te...",920076749081403392,1,0,0,Fund manager Novogratz agrees to advise ethere...,2017-10-16 23:59:25,/zentrade_online/status/920076749081403393,zentrade_online
1,Goodstockinvest,"<p class=""TweetTextSize js-tweet-text tweet-te...",920076678130307072,0,0,0,[Hb6EP.[F.R.E.E] [D.O.W.N.L.O.A.D]] Ethereum: ...,2017-10-16 23:59:08,/goodstockinvest/status/920076678130307072,goodstockinvest
2,Investors Europe,"<p class=""TweetTextSize js-tweet-text tweet-te...",920076645700198400,0,0,0,Now Boarding: Is #AXA's #Ethereum Test #Blockc...,2017-10-16 23:59:01,/onlineplatforms/status/920076645700198400,onlineplatforms
3,CRyptOTAtioN,"<p class=""TweetTextSize js-tweet-text tweet-te...",920076534836269056,0,0,0,"#IQT, #bitcoin, #ethereum, #cryptohttps://twit...",2017-10-16 23:58:34,/DNTihvin/status/920076534836269056,DNTihvin
4,AlexT,"<p class=""TweetTextSize js-tweet-text tweet-te...",920076505425817600,2,0,2,#pluscoin #dsplus #cryptocurrency #erc20 #bloc...,2017-10-16 23:58:27,/AlexandrTDS/status/920076505425817600,AlexandrTDS

# Let's Delete the columns which are not necessary for our analysis plan

In [14]:
del Oct['html']
del Oct['id']
del Oct['likes']
del Oct['replies']
del Oct['retweets']
del Oct['url']
del Oct['user']

,Unnamed: 0,text,timestamp
0,0,Why the XRP Ledger will decentralize further t...,2018-01-15 23:59:28
1,1,"Bitcoin: €11,077.51\r\nEthereum: €1,041.3\r\nL...",2018-01-15 23:59:13
2,2,Ethereum $ETH price: $1290.60 \r\n\r\nBinance ...,2018-01-15 23:59:06
3,3,Upcoming #ETC snapshot ≫ All Ethereum Classic ...,2018-01-15 23:59:06
4,4,"Sign up on Binance while you can , registrati...",2018-01-15 23:59:04

# Lets Convert the Json to csv.

In [ ]:
Jan.to_csv('Jantweets.csv')
print("Converted to CSV!!")

# Repeat the same step to other Json files.

In [6]:
Nov = pd.read_json('tweetsNov.json')
Nov.head()

,fullname,html,id,likes,replies,retweets,text,timestamp,url,user
0,Ricardo N,"<p class=""TweetTextSize js-tweet-text tweet-te...",930223743657566208,0,0,0,"Do not feel more lost on a trip, use the platf...",2017-11-13 23:59:57,/ricnnobre/status/930223743657566209,ricnnobre
1,CoinPilot,"<p class=""TweetTextSize js-tweet-text tweet-te...",930223621515046912,1,0,0,All Eyes On Dash As Currency Surges 60% Despit...,2017-11-13 23:59:28,/mycoinpilot/status/930223621515046912,mycoinpilot
2,Travelog View,"<p class=""TweetTextSize js-tweet-text tweet-te...",930223554238603264,0,0,0,#How #to #Mine #Bitcoin & #Earn Money | How to...,2017-11-13 23:59:12,/TravelogView/status/930223554238603264,TravelogView
3,Coin Spectator,"<p class=""TweetTextSize js-tweet-text tweet-te...",930223407978905600,0,0,0,Bitcoin Cash Hard Forks Blockchain In Bid to E...,2017-11-13 23:58:37,/coinspectator/status/930223407978905601,coinspectator
4,kemet km,"<p class=""TweetTextSize js-tweet-text tweet-te...",930223407748210688,0,0,0,im aware wats happening with the alts. however...,2017-11-13 23:58:37,/AdenKhalif/status/930223407748210688,AdenKhalif

In [23]:
del Nov['html']
del Nov['id']
del Nov['likes']
del Nov['replies']
del Nov['retweets']
del Nov['url']
del Nov['user']

In [27]:
Nov.to_csv('Novtweets.csv')

In [28]:
Dec = pd.read_json('tweetsDec.json')
Dec.head()

,fullname,html,id,likes,replies,retweets,text,timestamp,url,user
0,Cryptocurrency_Bot,"<p class=""TweetTextSize js-tweet-text tweet-te...",936746594854100992,0,0,0,"Korea price\nTime: 12/02 08:59:26\nBTC: 12,497...",2017-12-01 23:59:26,/VirtualMoneyBot/status/936746594854100992,VirtualMoneyBot
1,Finding Crypto(jeff),"<p class=""TweetTextSize js-tweet-text tweet-te...",936746520430362624,0,0,0,Earn Free Ethereum every 2-3 Minutes. Next Day...,2017-12-01 23:59:09,/jeffrey_verosil/status/936746520430362624,jeffrey_verosil
2,Global Stock Broker,"<p class=""TweetTextSize js-tweet-text tweet-te...",936746484577505280,0,0,0,Paying Rent With #Crypto? App for #Tenants Add...,2017-12-01 23:59:00,/globalbrokers/status/936746484577505281,globalbrokers
3,Daman M,"<p class=""TweetTextSize js-tweet-text tweet-te...",936746450838437888,1,0,1,'Microraiden' Payment Channels Go Live on Ethe...,2017-12-01 23:58:52,/daman7775/status/936746450838437889,daman7775
4,XBTmoney,"<p class=""TweetTextSize js-tweet-text tweet-te...",936746265886339072,0,0,0,Major Ethereum Scaling Solution Casper to Ente...,2017-12-01 23:58:08,/xbtmoney/status/936746265886339072,xbtmoney

In [29]:
del Dec['html']
del Dec['fullname']
del Dec['id']
del Dec['likes']
del Dec['replies']
del Dec['retweets']
del Dec['url']
del Dec['user']

In [30]:
Dec.to_csv('Dectweets.csv')

In [31]:
Jan = pd.read_json('tweetsJan.json')
del Jan['html']
del Jan['fullname']
del Jan['id']
del Jan['likes']
del Jan['replies']
del Jan['retweets']
del Jan['url']
del Jan['user']

In [32]:
Jan.to_csv('Jantweets.csv')

In [33]:
Feb = pd.read_json('tweetsFeb.json')
del Feb['html']
del Feb['fullname']
del Feb['id']
del Feb['likes']
del Feb['replies']
del Feb['retweets']
del Feb['url']
del Feb['user']

In [34]:
Feb.to_csv('Febtweets.csv')

In [35]:
Mar = pd.read_json('tweetsMarch.json')
del Mar['html']
del Mar['fullname']
del Mar['id']
del Mar['likes']
del Mar['replies']
del Mar['retweets']
del Mar['url']
del Mar['user']

In [36]:
Mar.to_csv('Marchtweets.csv')